services:
  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./server/db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - webnet

  web:
    build: .
    command: python server/app/main.py
    volumes:
      - .:/server
    expose:
      - 9000
    ports:
      - 9000:9000
    depends_on:
      - db
    networks:
      - webnet
    env_file:
      - .env

networks:
  webnet:

volumes:
  postgres_data:  # Define the volume for PostgreSQL data